name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Ontrack setup
        uses: ./
        id: ontrack
        with:
          github-token: ${{ github.token }}
          url: https://ontrack.nemerosa.net
          token: ${{ secrets.ONTRACK_TOKEN }}
          config: github.com
          indexation: 120

      - name: Ontrack build
        run: |
          ontrack-cli build setup --project ${{ steps.ontrack.outputs.project }} --branch ${{ steps.ontrack.outputs.branch }} --build ${{ github.run_number }}
          ontrack-cli build set-property --project ${{ steps.ontrack.outputs.project }} --branch ${{ steps.ontrack.outputs.branch }} --build ${{ github.run_number }} git-commit --commit ${{ github.sha }}
